COMMON_DISEASES = {
    "Viral Fever",
    "Dengue Fever",
    "Malaria",
    "Typhoid Fever",
    "Influenza",
    "Migraine",
    "Food Poisoning",
    "Common Cold",
    "Pneumonia",
    "Dehydration",
    "Epilepsy",
    "Asthma",
    "Zika Virus Disease",
    "Tuberculosis",
    "Hyperthyroidism",
}

RARE_DISEASES = {
    "Fabry Disease",
    "Gaucher Disease",
    "Huntington Disease",
    "Wilson Disease",
    "Rett Syndrome",
    "Tay-Sachs Disease",
    "Pompe Disease",
    "Amyotrophic Lateral Sclerosis",
    "Marfan Syndrome",
    "Ehlers-Danlos Syndrome",
    "Kawasaki Disease",
    "Batten Disease",
    "Niemann-Pick Disease",
    "Prader-Willi Syndrome",
    "Chronic Inflammatory Demyelinating Polyneuropathy",
    "Addison Disease",
    "Systemic Lupus Erythematosus",
    "Congenital Zika Syndrome",
    "Osteogenesis Imperfecta",
}

DISEASE_PROFILES = {
    "Viral Fever": {
        "category": "common_infectious",
        "age_group": "all",
        "hallmarks": {"fever", "fatigue", "body ache", "headache"},
        "rarity": "common",
    },
    "Dengue Fever": {
        "category": "common_vector_borne",
        "age_group": "all",
        "hallmarks": {"fever", "rash", "joint pain", "low platelet count", "headache"},
        "rarity": "common",
    },
    "Malaria": {
        "category": "common_vector_borne",
        "age_group": "all",
        "hallmarks": {"fever", "chills", "sweating", "fatigue"},
        "rarity": "common",
    },
    "Typhoid Fever": {
        "category": "common_infectious",
        "age_group": "all",
        "hallmarks": {"fever", "abdominal pain", "diarrhea", "fatigue"},
        "rarity": "common",
    },
    "Influenza": {
        "category": "common_respiratory",
        "age_group": "all",
        "hallmarks": {"fever", "cough", "sore throat", "body ache"},
        "rarity": "common",
    },
    "Migraine": {
        "category": "common_neurological",
        "age_group": "teen_adult",
        "hallmarks": {"headache", "nausea", "light sensitivity", "vomiting"},
        "rarity": "common",
    },
    "Food Poisoning": {
        "category": "common_gastrointestinal",
        "age_group": "all",
        "hallmarks": {"vomiting", "diarrhea", "abdominal pain", "dehydration"},
        "rarity": "common",
    },
    "Common Cold": {
        "category": "common_respiratory",
        "age_group": "all",
        "hallmarks": {"runny nose", "sore throat", "cough", "fever"},
        "rarity": "common",
    },
    "Pneumonia": {
        "category": "common_respiratory",
        "age_group": "all",
        "hallmarks": {"fever", "cough", "shortness of breath", "chest pain"},
        "rarity": "common",
    },
    "Dehydration": {
        "category": "common_metabolic",
        "age_group": "all",
        "hallmarks": {"dehydration", "dizziness", "fatigue", "vomiting"},
        "rarity": "common",
    },
    "Epilepsy": {
        "category": "common_neurological",
        "age_group": "all",
        "hallmarks": {"seizures", "loss of consciousness", "confusion"},
        "rarity": "common",
    },
    "Asthma": {
        "category": "common_respiratory",
        "age_group": "all",
        "hallmarks": {"wheezing", "shortness of breath", "cough", "chest tightness"},
        "rarity": "common",
    },
    "Zika Virus Disease": {
        "category": "common_vector_borne",
        "age_group": "all",
        "hallmarks": {"fever", "rash", "conjunctivitis", "joint pain", "headache"},
        "rarity": "common",
    },
    "Tuberculosis": {
        "category": "common_infectious",
        "age_group": "all",
        "hallmarks": {"persistent cough", "night sweats", "weight loss", "blood in sputum", "fatigue"},
        "rarity": "common",
    },
    "Hyperthyroidism": {
        "category": "common_endocrine",
        "age_group": "teen_adult",
        "hallmarks": {"palpitations", "sweating", "weight loss", "tremor", "heat intolerance", "goiter"},
        "rarity": "common",
    },
    "Fabry Disease": {
        "category": "rare_lysosomal_storage",
        "age_group": "child_adult",
        "hallmarks": {"neuropathic pain", "kidney issue", "vision loss", "fatigue"},
        "rarity": "rare",
    },
    "Gaucher Disease": {
        "category": "rare_lysosomal_storage",
        "age_group": "child_adult",
        "hallmarks": {"enlarged spleen", "bone pain", "anemia", "fatigue"},
        "rarity": "rare",
    },
    "Huntington Disease": {
        "category": "rare_neurological",
        "age_group": "adult",
        "hallmarks": {"chorea", "behavior change", "cognitive decline", "family history"},
        "rarity": "rare",
    },
    "Wilson Disease": {
        "category": "rare_metabolic",
        "age_group": "teen_adult",
        "hallmarks": {"liver dysfunction", "tremor", "behavior change", "jaundice"},
        "rarity": "rare",
    },
    "Rett Syndrome": {
        "category": "rare_neurodevelopmental",
        "age_group": "pediatric",
        "hallmarks": {"developmental regression", "seizures", "loss of speech", "hand wringing"},
        "rarity": "rare",
    },
    "Tay-Sachs Disease": {
        "category": "rare_neurodegenerative",
        "age_group": "pediatric",
        "hallmarks": {"developmental regression", "seizures", "vision loss", "hypotonia"},
        "rarity": "rare",
    },
    "Pompe Disease": {
        "category": "rare_metabolic_muscle",
        "age_group": "child_adult",
        "hallmarks": {"muscle weakness", "respiratory weakness", "fatigue", "delayed milestones"},
        "rarity": "rare",
    },
    "Amyotrophic Lateral Sclerosis": {
        "category": "rare_neuromuscular",
        "age_group": "adult",
        "hallmarks": {"progressive weakness", "muscle wasting", "difficulty swallowing", "respiratory weakness"},
        "rarity": "rare",
    },
    "Marfan Syndrome": {
        "category": "rare_connective_tissue",
        "age_group": "teen_adult",
        "hallmarks": {"tall stature", "lens dislocation", "aortic dilation", "joint laxity"},
        "rarity": "rare",
    },
    "Ehlers-Danlos Syndrome": {
        "category": "rare_connective_tissue",
        "age_group": "all",
        "hallmarks": {"joint hypermobility", "easy bruising", "skin hyperextensibility", "chronic pain"},
        "rarity": "rare",
    },
    "Kawasaki Disease": {
        "category": "rare_pediatric_vasculitis",
        "age_group": "pediatric",
        "hallmarks": {"fever", "rash", "red eyes", "swollen lymph nodes"},
        "rarity": "rare",
    },
    "Batten Disease": {
        "category": "rare_neurodegenerative",
        "age_group": "pediatric",
        "hallmarks": {"vision loss", "seizures", "developmental regression", "movement disorder"},
        "rarity": "rare",
    },
    "Niemann-Pick Disease": {
        "category": "rare_lysosomal_storage",
        "age_group": "pediatric",
        "hallmarks": {"enlarged spleen", "liver dysfunction", "developmental delay", "movement disorder"},
        "rarity": "rare",
    },
    "Prader-Willi Syndrome": {
        "category": "rare_genetic",
        "age_group": "pediatric",
        "hallmarks": {"hypotonia", "feeding difficulty", "obesity", "developmental delay"},
        "rarity": "rare",
    },
    "Chronic Inflammatory Demyelinating Polyneuropathy": {
        "category": "rare_autoimmune_neurology",
        "age_group": "adult",
        "hallmarks": {"progressive weakness", "numbness", "areflexia", "fatigue"},
        "rarity": "rare",
    },
    "Addison Disease": {
        "category": "rare_endocrine",
        "age_group": "teen_adult",
        "hallmarks": {"fatigue", "weight loss", "low blood pressure", "hyperpigmentation"},
        "rarity": "rare",
    },
    "Systemic Lupus Erythematosus": {
        "category": "rare_autoimmune",
        "age_group": "teen_adult",
        "hallmarks": {"joint pain", "rash", "fatigue", "fever"},
        "rarity": "rare",
    },
    "Congenital Zika Syndrome": {
        "category": "rare_congenital_infectious",
        "age_group": "pediatric",
        "hallmarks": {"microcephaly", "seizures", "developmental delay", "vision loss"},
        "rarity": "rare",
    },
    "Osteogenesis Imperfecta": {
        "category": "rare_connective_tissue",
        "age_group": "pediatric",
        "hallmarks": {"frequent fractures", "blue sclera", "hearing loss", "growth delay", "bone pain"},
        "rarity": "rare",
    },
}

EMERGENCY_SYMPTOMS = {
    "shortness of breath",
    "chest pain",
    "seizures",
    "loss of consciousness",
    "respiratory weakness",
    "low blood pressure",
    "aortic dilation",
}

MILD_COMMON_SYMPTOMS = {
    "fever",
    "fatigue",
    "headache",
    "cough",
    "sore throat",
    "runny nose",
    "body ache",
    "nausea",
}
